spring:
  #autoconfigure:
    #exclude:
     # - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  application:
    name: shop

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
      format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/shop-1
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
server:
  port: 8081

jwt:
  secret: myscrecetKey_1